#!/bin/bash

CURRENT_BRANCH=`git branch | grep '^\*' |  sed -e 's/* //'`
for BRANCH in `git branch | sed -e 's/* //'`
do
	if [[ $BRANCH =~ 'master' ]]
	then
		continue
	fi
	git checkout $BRANCH
	if [[ $? -ne 0 ]]
	then
		echo "ERROR: Cannot change branch."
		exit 1
	fi
	find . -type f -name '.DS_Store' -exec rm {} \;
	rm -rf T-Mobile_US.ipcc
	BUNDLE_NAME="TMobile_US-$BRANCH.ipcc"
	echo Making carrier bundle $BUNDLE_NAME
	zip -r -y "../$BUNDLE_NAME" Payload/
done
git checkout $CURRENT_BRANCH
