#!/bin/bash
#===============================================================================
#
#          FILE:  make-bundle
#
#         USAGE:  ./make-bundle
#
#   DESCRIPTION:  Makes T-Mobile US carrier bundles.
#
#        AUTHOR:  SpookyET, spookyet@gmail.com
#       VERSION:  1.0.2
#       CREATED:  2009-06-30 23:34:57+00:00
#===============================================================================

CURRENT_BRANCH=`git branch | grep '^\*' |  sed -e 's/* //'`
VERSION=`git tag | tail`
for BRANCH in `git branch | sed -e 's/* //'`
do
	if [[ $BRANCH =~ 'master' ]]
	then
		continue
	fi
	git checkout $BRANCH
	if [[ $? -ne 0 ]]
	then
		echo "ERROR: Cannot change branch."
		exit 1
	fi
	find . -type f -name '.DS_Store' -exec rm {} \;
	rm -rf T-Mobile_US.ipcc
	BUNDLE_NAME="TMobile_us_$BRANCH_$VERSION.ipcc"
	echo Making carrier bundle $BUNDLE_NAME
	zip -r -y "$BUNDLE_NAME" Payload/
done
zip -y "TMobile_us_carrier_bundles_$VERSION.zip" README.txt TMobile_us*
rm -f *.ipcc
git checkout $CURRENT_BRANCH
